version: '3' # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
    db: # 서비스 명
        image: mysql:5.7.30 # 사용할 이미지
        container_name: to-do-noti2007-mysql-db # 컨테이너 이름 설정
        ports:
            - '3306:3306' # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
        environment: # -e 옵션
            MYSQL_ROOT_PASSWORD: '1234' # MYSQL 패스워드 설정 옵션
            # MYSQL_ROOT_HOST: '%'
        command: # 명령어 실행
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./init/:/docker-entrypoint-initdb.d/ # db 생성에 이어서 해당 .sql에 포함된 구문을 추가로 수행 (DDL)
        #   - /home/ec2-user/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    # backend:
    #     container_name: to-do-noti2007-spring-backend
    #     build: ./backend
    #     ports:
    #         - '8081:8081'
    #     depends_on: 
    #         - db
    frontend:
        container_name: to-do-noti2007-frontend
        build: ./frontend
        ports: 
            - '80:80'
        # depends_on: 
        #     - backend
